version: '3.8'

services:
  fastapi:
    build:
      context: ./backend/fastapi
      dockerfile: Dockerfile
    container_name: fastapi-production
    ports:
      - "8002:8000"
    networks:
      - app-network

  streamlit:
    build:
      context: ./frontend/streamlit
      dockerfile: Dockerfile
    container_name: streamlit-production
    ports:
      - "8502:8501"
    environment:
      - API_BASE=http://fastapi:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
