sonar.projectKey=thread-quest
sonar.projectName=Thread Quest

sonar.sources=backend, frontend

sonar.exclusions=**/node_modules/**,**/coverage/**,**/uploads/**,archive/**,.scannerwork/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8